name: Test
on:
  # Run CI on all pushes to the master and release/** branches, and on all new
  # pull requests, and on all pushes to pull requests (even if a pull request
  # is not against master).
  push:
    branches:
      - "master"
      - "release/**"
  pull_request:
  schedule:
    - cron: "0 0,12 * * *"

concurrency:
  group: ${{ github.ref_name || github.sha }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
jobs:
  unit-test:
#    if: github.repository_owner == 'getsentry'
    runs-on: ubuntu-latest
    name: "unit tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Compose
        uses: ./get-compose-action

      - name: Unit Tests
        run: ./unit-test.sh

  integration-test:
#    if: github.repository_owner == 'getsentry'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container_engine: ['docker', 'podman']
    name: integration test (${{ matrix.container_engine }})
    env:
      REPORT_SELF_HOSTED_ISSUES: 0
      SELF_HOSTED_TESTING_DSN: ${{ vars.SELF_HOSTED_TESTING_DSN }}
      CONTAINER_ENGINE_PODMAN: ${{ matrix.container_engine == 'podman' && '1' || '0' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Podman
        if: matrix.container_engine == 'podman'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends podman
          # TODO: Replace below with podman-compose
          #       We need this commit to be able to work: https://github.com/containers/podman-compose/commit/8206cc3ea277eee6c2e87d4cd66eba8eae3d44eb
          pip3 install --user https://github.com/containers/podman-compose/archive/main.tar.gz
          echo "PODMAN_COMPOSE_PROVIDER=podman-compose" >> $GITHUB_ENV
          echo "PODMAN_COMPOSE_WARNING_LOGS=false" >> $GITHUB_ENV

      - name: Use action from local checkout
        uses: './'
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Inspect failure
        if: failure()
        run: |
          docker compose ps
          docker compose logs
